FROM python:3.9-slim-buster

RUN apt-get update && apt-get install -y openjdk-11-jre-headless

RUN pip install kafka-python pyspark influxdb-client

COPY test_consumer.py /

#CMD ["python", "/test_consumer.py"]

CMD sleep infinity
